### ISSUE TITLE
Inner loop resumes after break in OSWEB 1.3.8

### ISSUE THREAD

**Issue by louweal** [smathot/osweb#30]
When breaking from an inner loop using 'break if' it doesn't start from the beginning in the next trial (=outer loop). 
The option 'Resume after break' was **not** toggled. 

The bug does not appear in OSWEB 1.3.3. 

Demo experiment: 
[OSWebBug1.3.8_Break_If.zip](https://github.com/open-cogsci/osweb/files/5083076/OSWebBug1.3.8_Break_If.zip)

**Comment by smathot** [comment]
Thanks for pointing this out. I attached another example, slightly simplified. This should show 'a' five times in a row, because the 'a' is the first row of the block loop, and the block loop is broken after one cycle (and then restarted five times). But in OSWeb, it shows 'a', 'c', 'e', 'b', 'd', thus not starting from scratch (as it should), and mysteriously skipping one row each time.

[osweb-loops.zip](https://github.com/open-cogsci/osweb/files/5094912/osweb-loops.zip)
