### ISSUE TITLE
"Required" attribute (HTML)

### ISSUE THREAD

**Issue by ImhChr** [smathot/osweb#91]
In the HTML widget, all of the items that feature the "required" attribute currently absolutely have to be selected. For example, if the required attribute is used for radio buttons, which should result in the question as a whole being mandatory, currently the exact item with the attribute is mandatory. If it's added to all options, the question cannot be answered anymore because all items are then mandatory, which is impossible since only one can be selected at a time in this case.

**Comment by smathot** [comment]
I will fix this for radio buttons, because as far as I can tell these are the only input elements to which this issue applies. But I'm not entirely sure, because the intended behavior of `required` is not very clearly documented for edge cases (e.g. [here](https://www.w3schools.com/tags/att_input_required.asp)). Let me know if this issue re-occurs elsewhere.
